# 1. set
* 수학의 집합과 비슷한 형태로 순서가 없기 때문에 어떤 값이 먼저 나올지 알 수 없고, 중복되는 데이터를 허용하지 않음
* 딕셔너리처럼 중괄호를 사용해서 선언하지만 key는 존재하지 않고 value만 존재

### 1-1. set만들기

In [3]:
s1 = {1,3,5,7}
print(s1)

s2 = set([1,3,5,7])
print(s2)

s3 = {1,3,5,7,5,3,9}
print(s3)

{1, 3, 5, 7}
{1, 3, 5, 7}
{1, 3, 5, 7, 9}

In [8]:
print(2 in s3)
print(5 in s3)
print(3 not in s3)  # not : True를 False로, False를 True로 변경

False
True
False

### 1-2. 함수

In [18]:
# add() : set에 단일 데이터를 추가
s1 = {100, 200}
s1.add(150)
print(s1) # 순서가 정의되지 않음
s1.add(20)
print(s1)

# update() : set에 여러 데이터를 한번에 추가
s2 = {10,20,30}
s2.update([40,50,60,20])
print(s2)

# remove() : set의 데이터를 제거,
# 제거할 데이터가 없으면 에러
s2.remove(50)
print(s2)
# s2.remove(50) # KeyError: 50

# discard() : set의 데이터를 제거,
# 제거할 데이터가 없어도 에러가 발생하지 않음
s2.discard(30)
print(s2)
s2.discard(30)
print(s2)

# copy() : set을 복사
s3 = {10,20,30}
s4 = s3.copy()
print(s3)
print(s4)

{200, 100, 150}
{200, 100, 20, 150}
{40, 10, 50, 20, 60, 30}
{40, 10, 20, 60, 30}
{40, 10, 20, 60}
{40, 10, 20, 60}
{10, 20, 30}
{10, 20, 30}

In [22]:
print(s3)
# TypeError: 'set' object does not support item assignment
# set은 슬라이싱을 지원하지 않는다.
s3[0] = 100
print(s3)

{10, 20, 30}

TypeError: ignored

## 1-3. set연산자

In [32]:
s1 = {10,20,30,40,50}
s2 = {30,40,50,60,70}

# 합집합(union) : |
result = s1 | s2
print(result)
result = s1.union(s2)
print(result)

# 교집합(intersection) : &
result = s1 & s2
print(result)
result = s1.intersection(s2)
print(result)

# 차집합(defference) : -
result = s1 - s2
print(result)
result = s1.difference(s2)
print(result)

# 대칭 차집합(symmetric_difference) : ^
result = s1 ^ s2
print(result)
result = s1.symmetric_difference(s2)
print(result)

{70, 40, 10, 50, 20, 60, 30}
{70, 40, 10, 50, 20, 60, 30}
{40, 50, 30}
{40, 50, 30}
{10, 20}
{10, 20}
{20, 70, 10, 60}
{20, 70, 10, 60}